import John from '../assets/John Doe.png';

export const data = [
  {
    sr: 1,
    name: 'Pessoa 1',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
  },
  {
    sr: 2,
    name: 'Pessoa 2',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Não feito',
    acc: 'Feito',
  },
  {
    sr: 3,
    name: 'Pessoa 3',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Não feito',
  },
  {
    sr: 4,
    name: 'Pessoa 4',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Não feito',
    acc: 'Não feito',
  },
  {
    sr: 5,
    name: 'Pessoa 5',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
  },
  {
    sr: 6,
    name: 'Pessoa 6',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
  },
  {
    sr: 7,
    name: 'Pessoa 7',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
  },
  {
    sr: 8,
    name: 'Pessoa 8',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
  },
  {
    sr: 9,
    name: 'Pessoa 9',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Em andamento',
    acc: 'Em andamento',
  },
  {
    sr: 10,
    name: 'Pessoa 10',
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Em andamento',
    acc: 'Em andamento',
  },
  {
    sr: 11,
    name: 'Pessoa 11',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Em andamento',
    acc: 'Em andamento',
  },
  {
    sr: 12,
    name: 'Pessoa 12',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Em andamento',
    acc: 'Em andamento',
  },
]