import John from '../assets/John Doe.png';

export const data = [
  {
    sr: 1,
    name: 'Pessoa 1',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
    duties: [
      {
        date: '12/04',
        startTime: '-',
        finishTime: '-',
        duration: 2,
      },
      {
        date: '13/04',
        duration: 2,
      },
      {
        date: '14/04',
        duration: 2,
      },
      {
        date: '15/04',
        duration: 2,
      },
      {
        date: '16/04',
        duration: 2,
      },
      {
        date: '17/04',
        duration: 2,
      },
      {
        date: '18/04',
        duration: 2,
      },
    ],
    about: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris auctor libero justo, sed mattis sem sagittis non. In eget mauris erat. Donec ultricies quis nibh eget vestibulum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris auctor libero justo, sed mattis sem sagittis non. In eget mauris erat. Donec ultricies quis nibh eget vestibulumLorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris auctor libero justo, sed mattis sem sagittis non. In eget mauris erat. Donec ultricies quis nibh eget vestibulum',
  },
  {
    sr: 2,
    name: 'Pessoa 2',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Não feito',
    acc: 'Feito',
    duties: [
      {
        date: '12/04',
        startTime: '-',
        finishTime: '-',
        duration: 2,
      },
      {
        date: '13/04',
        duration: 2,
      },
      {
        date: '14/04',
        duration: 2,
      },
      {
        date: '15/04',
        duration: 2,
      },
      {
        date: '16/04',
        duration: 2,
      },
      {
        date: '17/04',
        duration: 2,
      },
      {
        date: '18/04',
        duration: 2,
      },
    ],
  },
  {
    sr: 3,
    name: 'Pessoa 3',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Não feito',
    duties: [
      {
        date: '12/04',
        startTime: '-',
        finishTime: '-',
        duration: 2,
      },
      {
        date: '13/04',
        duration: 2,
      },
      {
        date: '14/04',
        duration: 2,
      },
      {
        date: '15/04',
        duration: 2,
      },
      {
        date: '16/04',
        duration: 2,
      },
      {
        date: '17/04',
        duration: 2,
      },
      {
        date: '18/04',
        duration: 2,
      },
    ],
  },
  {
    sr: 4,
    name: 'Pessoa 4',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Não feito',
    acc: 'Não feito',
    duties: [
      {
        date: '12/04',
        startTime: '-',
        finishTime: '-',
        duration: 2,
      },
      {
        date: '13/04',
        duration: 2,
      },
      {
        date: '14/04',
        duration: 2,
      },
      {
        date: '15/04',
        duration: 2,
      },
      {
        date: '16/04',
        duration: 2,
      },
      {
        date: '17/04',
        duration: 2,
      },
      {
        date: '18/04',
        duration: 2,
      },
    ],
  },
  {
    sr: 5,
    name: 'Pessoa 5',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
    duties: [
      {
        date: '12/04',
        startTime: '-',
        finishTime: '-',
        duration: 2,
      },
      {
        date: '13/04',
        duration: 2,
      },
      {
        date: '14/04',
        duration: 2,
      },
      {
        date: '15/04',
        duration: 2,
      },
      {
        date: '16/04',
        duration: 2,
      },
      {
        date: '17/04',
        duration: 2,
      },
      {
        date: '18/04',
        duration: 2,
      },
    ],
  },
  {
    sr: 6,
    name: 'Pessoa 6',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
  },
  {
    sr: 7,
    name: 'Pessoa 7',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
  },
  {
    sr: 8,
    name: 'Pessoa 8',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Feito',
    acc: 'Feito',
  },
  {
    sr: 9,
    name: 'Pessoa 9',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Em andamento',
    acc: 'Em andamento',
  },
  {
    sr: 10,
    name: 'Pessoa 10',
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Em andamento',
    acc: 'Em andamento',
  },
  {
    sr: 11,
    name: 'Pessoa 11',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Em andamento',
    acc: 'Em andamento',
  },
  {
    sr: 12,
    name: 'Pessoa 12',
    file: John,
    position: 'Gerente de projetos',
    facebook: 'https://www.facebook.com',
    instagram: 'https://www.instagram.com/?hl=pt-br',
    linkedin: 'https://www.linkedin.com/home',
    onDuty: 'Em andamento',
    acc: 'Em andamento',
  },
]